name: ght-render-repo
on:
  pull_request:
    branches:
      - ght/master
  push:
    branches:
      - ght/master

jobs:
  ght-render-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: sodre/ght-render@master
        with:
          template: sodre/ght-pypackage@f-external-ght
      - name: Push changes to ght/master
        run: git push --set-upstream origin HEAD:${{ github.ref }}

      - name: Create pull-request against master
        uses: octokit/request-action@v2.x
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/:repository/pulls
          repository: ${{ github.repository }}
          title: Merge ght/master into master
          head: ght/master
          base: master
          body: |
            |
            Modifications to ght/master were detected.
              - [ ] Review the changes
              - [ ] Fix the errors by committing back to ght/master
              - [ ] Do **not** use Squash or Rebase
              - [ ] Do **not** delete the ght/master branch
