name: ght-render-repo
on:
  pull_request:
    branches:
      - ght/master
  push:
    branches:
      - ght/master

jobs:
  ght-render-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: sodre/ght-render@master
        with:
          template: sodre/ght-pypackage@f-external-ght
      - name: Commit changes to ${{ github.hread_ref }}
        run: git push --set-upstream origin HEAD:${{ github.head_ref }} --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        if: false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: ght/render
          branch-suffix: timestamp
          commit-message: |
            Render ght/master into master

            This commit was obtained as follows:
              1. Checkout the last merged rendering of ght/master
                 git checkout ${{ steps.last-render.outputs.treeish }}
              2. Replace its contents with ght/master
                 git rm -rf .
                 git checkout origin/ght/master -- .
              3. Load the configured ght.yaml from PR #${{ github.event.number }} file
                 git checkout ${{ github.sha }} -- .github/ght.yaml
              4. Execute the rendering steps
                 .github/bin/ght-render.sh render_tree_structure
                 .github/bin/ght-render.sh render_tree_ght_content
                 .github/bin/ght-render.sh render_tree_content
                 .github/bin/ght-render.sh finish
              5. Commit
                 git commit

            Close #${{ github.event.number }}

          title: Render ght/master into master
          reviewers: ${{ github.actor }}
          labels: ght
          body: |
            Please review the changes and fix any conflicts before merging.

            If the configuration variables were incorrect, please close this PR and
            use your ght-configure PR #${{ github.event.number }} to edit the values.
