name: ght-render-repo
on:
  pull_request:
    branches:
      - ght/master
  push:
    branches:
      - ght/master

jobs:
  ght-render-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: sodre/ght-render@master
        with:
          template: sodre/ght-pypackage@f-external-ght
      - name: Commit changes to ${{ github.hread_ref }}
        run: git push --set-upstream origin HEAD:${{ github.ref }}

      - uses: octokit/request-action@v2.x
        if: github.event_name == 'push'
        with:
          route: POST /repos/:repository/pulls
          repository: ${{ github.repository }}
          title: '[ght]: update rendered template'
          head: ght/master
          base: master
          body: |
            Modifications to ght/master were detected. Please do the following:

              - [ ] Review the changes
              - [ ] Fix any errors by committing back to ght/master`
              - [ ] When ready to merge do **not** use Squash or Rebase
