name: ght-render-repo
on:
  pull_request:
    branches:
      - ght/master
  push:
    branches:
      - ght/master

jobs:
  ght-render-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: sodre/ght-render@master
        with:
          template: sodre/ght-pypackage@f-external-ght
      - name: Commit changes to ${{ github.hread_ref }}
        run: git push --set-upstream origin HEAD:${{ github.ref }}

      - name: Pull Request on ght/master push
        if: github.event_name == 'push'
        uses: vsoch/pull-request-action@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ght/master
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_TITLE: '[ght]: update rendered template'
          PULL_REQUEST_BODY: |
            Modifications to ght/master were detected. Please do the following:

              - [ ] Review the changes
              - [ ] Fix any errors by committing back to ght/master`
              - [ ] When ready to merge do **not** use Squash or Rebase

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        if: false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: refs/remotes/origin/master
          branch: ght/master
          branch-suffix: none
          title: Render ght/master into master
          reviewers: ${{ github.actor }}
          labels: ght
          body: |
            Modifications to ght/master were detected. Please do the following:

              - [ ] Review the changes
              - [ ] Fix any errors by committing back to ght/master`
              - [ ] When ready to merge do **not** use Squash or Rebase
